# Generated by Django 4.1 on 2023-01-18 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Есімі')),
                ('last_name', models.CharField(max_length=150, verbose_name='Тегі')),
                ('rejim', models.CharField(max_length=255, verbose_name='Жұмыс уақыты')),
                ('position', models.CharField(max_length=150, verbose_name='Кәсіби мамандығы')),
            ],
            options={
                'verbose_name': 'Дәрігер',
                'verbose_name_plural': 'Дәрігерлер',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Есімі')),
                ('last_name', models.CharField(max_length=150, verbose_name='Тегі')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('jsn', models.CharField(max_length=12, verbose_name='ЖСН')),
                ('birthday', models.DateField(verbose_name='Туылған күні')),
                ('gender', models.CharField(max_length=4, verbose_name='Жынысы')),
                ('national', models.CharField(max_length=20, verbose_name='Ұлты')),
                ('address', models.CharField(max_length=1000, verbose_name='Мекен-жайы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенттер',
            },
        ),
        migrations.CreateModel(
            name='Poliklinika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255, verbose_name='Поликлиника аты')),
                ('address', models.CharField(max_length=255, verbose_name='Поликлиника мекен-жайы')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Поликлиника',
                'verbose_name_plural': 'Поликлиника',
            },
        ),
        migrations.CreateModel(
            name='Zapis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Статус')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Жазылым уақыты')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Жазылған уақыты')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.patient')),
            ],
            options={
                'verbose_name': 'Жазылым',
                'verbose_name_plural': 'Жазылымдар',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='poliklinika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.poliklinika', verbose_name='Поликлина'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы'),
        ),
    ]
