# Generated by Django 4.1 on 2023-01-18 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Есімі')),
                ('last_name', models.CharField(max_length=150, verbose_name='Тегі')),
                ('department', models.CharField(max_length=150, verbose_name='Бөлімі')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Күні')),
                ('time', models.TimeField(verbose_name='Уақыты')),
                ('question', models.TextField(max_length=5000, verbose_name='Сұрағы')),
            ],
            options={
                'verbose_name': 'Кеңес алушы',
                'verbose_name_plural': 'Кеңес алушылар',
            },
        ),
        migrations.AlterField(
            model_name='doctor',
            name='poliklinika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.poliklinika', verbose_name='Поликлиника'),
        ),
        migrations.AlterField(
            model_name='zapis',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctor', verbose_name='Дәрігер'),
        ),
        migrations.AlterField(
            model_name='zapis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.patient', verbose_name='Пациент'),
        ),
    ]
