# Generated by Django 4.1 on 2023-01-18 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_consultation_alter_doctor_poliklinika_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctor', verbose_name='Учаскелік дәрігер'),
        ),
        migrations.AlterField(
            model_name='zapis',
            name='data',
            field=models.DateTimeField(verbose_name='Жазылым уақыты'),
        ),
        migrations.CreateModel(
            name='DoctorAtHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Адресс')),
                ('data', models.DateTimeField(verbose_name='Жазылым уақыты')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Жазылған уақыты')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctor', verbose_name='Дәрігер')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Үйге шақырту',
                'verbose_name_plural': 'Үйге шақыртулар',
            },
        ),
    ]
