# Generated by Django 4.1 on 2023-01-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_birthday_patient_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='birth',
            new_name='birthday',
        ),
    ]
